=== eugene-choy-2016/EI_Project/TrainBreakDown/Tibco_Project/Schemas/new_breakdown.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!--Created with Liquid Studio 2017 - Developer Bundle Edition (Education) 15.1.16.7872 (https://www.liquid-technologies.com)-->
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="breakdown">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="train_id" type="xs:int" minOccurs="1" maxOccurs="1" />
                <xs:element name="faultType" type="xs:string" minOccurs="1" maxOccurs="1" />
                <xs:element name="timestamp" type="xs:dateTime" minOccurs="1" maxOccurs="1" />
                <xs:element name="coordinates" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="lat" type="xs:decimal" minOccurs="1" maxOccurs="1" />
                            <xs:element name="long" type="xs:decimal" minOccurs="1" maxOccurs="1" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="remark" type="xs:string" minOccurs="1" maxOccurs="1" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== eugene-choy-2016/EI_Project/TrainBreakDown/msgResource/breakdown.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<breakdown xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation = "C:\\Users\\i-am-\\OneDrive - Singapore Management University\\Year 2\\EI\\Project\\EI_Project\\TrainBreakDown\\new_breakdown.xsd">
	<train_id>3</train_id>
	<faultType>Train Fault</faultType>
	<timestamp>22/03/18 15:00</timestamp>
	<coordinates>
		<lat>1.3272383</lat>
		<long>103.9443528</long>
	</coordinates>
	<remark>Tanah Merah Station</remark>
</breakdown>
